server:
  port: 9191
spring:
  cloud:
    gateway:
      routes:
        - id: authentication
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/login,/api/v1/auth/register,/api/v1/auth/verify-email/{token},/api/v1/users/forgot-password,/api/v1/users/reset-password/{token}

        - id: get-current-user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/me, /api/v1/auth/logout
          filter:
            - AuthenticationFilter


jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
