server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/frms_flight_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        batch_versioned_data: true

redis:
  host: localhost
  port: 6379
  time-to-leave: 3600000