server:
  port: 8084

spring:
  sleuth:
    sampler:
      probability: 1

  zipkin:
    base-url: http://127.0.0.1:9411/

  datasource:
    url: jdbc:postgresql://localhost:5432/frms_payment_db
    username: postgres
    password: postgres
  jpa:
    #    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        batch_versioned_data: true
#  sql:
#    init:
#      mode: always
management:
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: payment-service-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer